### ISSUE TITLE
Missing features?

### ISSUE THREAD

**Issue by jramshur** [mrquincle/memoto#1]
On you readme you list the following features, but I don't see any mention of how to do these last items. I managed to use your python code to get a directory list and read a file Great work by the way! However I'm very curious about the last features you mentioned. I didn't see anything in the code either.
- enable a developmental option on the Memoto
  subsequently the Memoto becomes available in a normal fashion to almost all modern operating systems
- change the frequency with which you snap pictures
- use the Memoto as a fancy USB drive which also happens to take pictures

**Comment by mrquincle** [comment]
@jramshur Those things are not missing. They can really be done. Did you actually connect via telnet to the device? If you go through the files as also listed in https://github.com/mrquincle/memoto/blob/master/dump/files there will be scripts that actually read the `.dev_options.dat` file that is mentioned in the `README.md` file. I don't know the name of the script out of the top of my head, so please just grep on `.dev_options` for now.

There is then an option to set the update frequency.

However, much more important, you can do whatever you want! You can create your own scripts or programs that allow you to play tetris. Your mind is the only limitation.
