### ISSUE TITLE
USB Ethernet device is active, but not running any services

### ISSUE THREAD

**Issue by oilerssuck** [mrquincle/memoto#2]
All steps worked up until the last one.  Device is now a USB Ethernet device, and can have an IP address bound to it.  There are no services running on the narrative clip however (portscan turns up nothing, and attempting to telnet to standard ports shows nothing)

Any ideas of how i can reverse the process without being able to telnet in, would be welcome.

**Comment by mrquincle** [comment]
What does `lsusb` list? And what is the output of `sudo python memoto.py list /mnt/storage`?

**Comment by oilerssuck** [comment]
It doesnt mount /mnt/storage when plugged in anymore, just immediately brings up the USB ethernet device (usb ID of 0525:a4a1). 

lsusb lists the Linux USB Ethernet device (0525:a4a1), and running memoto.py only prints out 'You don't need to use this script anymore...'  I can get more detailed output once I have the clip on me again.  The Ethernet connection I believe only stays active for 30 seconds, before needing the "sudo ifconfig usb0 192.168.2.2".  

After assigning the IP I can run a sudo nmap -p- 192.168.2.2 long enough to confirm that all 65535 ports are closed but the host is up.

**Comment by mrquincle** [comment]
You should NOT do `sudo ifconfig usb0 192.168.2.2`, but you have to pick another IP address, for example `sudo ifconfig usb0 192.168.2.10`, as long is it is not `.2`. Then try `sudo arp-scan -l -I usb0` to find out if there is an IP in your netmask. I think you have scanned your own machine.

**Comment by oilerssuck** [comment]
sorry, I did use the .10 initially, later changing it to the .2 address, I also tried to set it to 192.168.3.10 with the same results.  I will attempt it again, and do an arp scan to see if there are any results.  The machine I was using was using an IP address from the 192.168.1.1/24 IP block however.  Currently Ive left the device out, so that the battery drains, with the hope that on a hard boot of the system, the init.d will fire up the telnet and ftp services.

**Comment by mrquincle** [comment]
If you have a static IP address from the `192.168.1.1/24` block you will not be able to find `192.168.2.xxx`.

**Comment by oilerssuck** [comment]
ok, I just managed to get it to work, first I built a new VM and configured it, then your last post made me start looking at the routing tables and the arp entries on the system, and then between that and re-reading your documentation, it finally clicked that the IP I was assigning to usb0 wasnt the IP that the memoto was using, the memoto was always going to get 192.168.2.2.  reconfigured usb0 to use 192.168.2.10/24 confirmed the arp and that there was a route, and I was then able to connect to the memoto on 192.168.2.2.  previously I had been trying to get all connections to route through eth0 which is what I believe was causing my headaches.

Thanks again for the responses, I'll write up some supplemental documentation to clarify a couple of things that caused me the confusion, and send it to you. (and then you can deleted it or whatever ;) )

**Comment by mrquincle** [comment]
Glad to see that you figured it out! :-)

**Comment by oilerssuck** [comment]
After re-reading it, I figured the easiest thing for clarification was to update the tl;dr section to add in a couple of command/directory changes, and add some notes to the telnet

sudo apt-get install python3.4 libusb-1.0-0 git    **# or use your favorite installer**
git clone https://github.com/walac/pyusb           **# install pyusb for usb.core**
cd pyusb
sudo python setup.py install
cd ..
git clone https://github.com/mrquincle/memoto      **# install this repos**
cd memoto
sudo python memoto.py list /mnt/storage
sudo python memoto.py upload /mnt/storage/ .dev_options.dat
**# now reconnect the USB cable**
sudo ifconfig usb0 192.168.2.10 netmask 255.255.255.0 broadcast 192.168.2.255                    **# set static IP (disable DHCP!)**
telnet 192.168.2.2                                            **#192.168.2.2 is the IP address the memoto is**
                                                                        **# configured to use, 192.168.2.10 is the address you** 
                                                                         **#assign to usb0 in order to route through to the memotos pre-configured IP address**
